<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="apples-MacBook-Pro.local" name="com.citi.mobileAutomation.test_ID.TestDashBoard_L2_L3_ID" tests="4" failures="0" timestamp="23 Jan 2019 10:16:22 GMT" time="0.000" errors="1">
  <testcase name="test_AccountDetails_100_savings" time="0.000" classname="com.citi.mobileAutomation.test_ID.TestDashBoard_L2_L3_ID">
    <error type="org.testng.TestNGException" message="
Data Provider public java.lang.Object[][] com.citi.mobileAutomation.dataProviders.DataProvider_ID.dataRequiredForTest_Account_Details_100_Savings_ID() throws java.io.IOException returned a null value">
      <![CDATA[org.testng.TestNGException: 
Data Provider public java.lang.Object[][] com.citi.mobileAutomation.dataProviders.DataProvider_ID.dataRequiredForTest_Account_Details_100_Savings_ID() throws java.io.IOException returned a null value
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:133)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test_AccountDetails_100_savings -->
  <testcase name="test_AccountDetails_100_MF" classname="com.citi.mobileAutomation.test_ID.TestDashBoard_L2_L3_ID">
    <skipped/>
  </testcase> <!-- test_AccountDetails_100_MF -->
  <testcase name="test_AccountDetails_100_SB" classname="com.citi.mobileAutomation.test_ID.TestDashBoard_L2_L3_ID">
    <skipped/>
  </testcase> <!-- test_AccountDetails_100_SB -->
  <testcase name="test_AccountDetails_100_Checkings" classname="com.citi.mobileAutomation.test_ID.TestDashBoard_L2_L3_ID">
    <skipped/>
  </testcase> <!-- test_AccountDetails_100_Checkings -->
</testsuite> <!-- com.citi.mobileAutomation.test_ID.TestDashBoard_L2_L3_ID -->
