<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="RDT039" name="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455" tests="24" failures="4" timestamp="20 Mar 2019 15:03:03 GMT" time="1031.445" errors="0">
  <testcase name="gettingDataEPP" time="154.510" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="25.607" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="31.586" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="8.754" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="47.380" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:75)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:51)
at com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455.gettingDataEPP(Test__TW_EPP_Transactions_455.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="14.196" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="11.794" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="18.074" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="447.609" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="11.306" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="5.917" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="15.641" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="9.876" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="5.384" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:60)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:51)
at com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455.gettingDataEPP(Test__TW_EPP_Transactions_455.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="61.636" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:75)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:51)
at com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455.gettingDataEPP(Test__TW_EPP_Transactions_455.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="11.692" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="12.845" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="10.272" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="47.816" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:75)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:51)
at com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455.gettingDataEPP(Test__TW_EPP_Transactions_455.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="23.369" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="9.870" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="13.924" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="20.257" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
  <testcase name="gettingDataEPP" time="12.130" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455"/>
</testsuite> <!-- com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_455 -->
