<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="RDT039" name="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings" tests="28" failures="3" timestamp="01 May 2019 10:00:51 GMT" time="1353.311" errors="0">
  <testcase name="gettingDataEPP" time="21.241" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="60.170" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="64.429" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="5.974" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="6.068" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="139.605" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="26.991" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="14.346" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="15.706" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="13.746" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="50.087" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="6.518" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="14.151" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="13.238" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings">
    <failure type="java.lang.AssertionError" message="expected [Your transaction] but found [Savings]">
      <![CDATA[java.lang.AssertionError: expected [Your transaction] but found [Savings]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:9)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:34)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings.gettingDataEPP(Test__EMEA_RU_AD_100_Savings.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="7.411" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="43.112" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings">
    <failure type="java.lang.AssertionError" message="expected [ 31.10.2022] but found [31.10.2022]">
      <![CDATA[java.lang.AssertionError: expected [ 31.10.2022] but found [31.10.2022]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:9)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:34)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings.gettingDataEPP(Test__EMEA_RU_AD_100_Savings.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="188.595" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="13.744" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="60.660" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="47.422" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="281.487" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="71.260" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:75)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:48)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings.gettingDataEPP(Test__EMEA_RU_AD_100_Savings.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="5.923" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="8.034" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="57.040" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="41.352" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="15.901" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
  <testcase name="gettingDataEPP" time="59.100" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings"/>
</testsuite> <!-- com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Savings -->
