<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="RDT039" name="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400" tests="36" failures="1" timestamp="20 Mar 2019 14:06:28 GMT" time="924.467" errors="4">
  <testcase name="gettingDataEPP" time="61.815" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="10.525" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="23.163" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="5.137" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:13)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:51)
at com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400.gettingDataEPP(Test__TW_EPP_Transactions_400.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="15.162" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="18.248" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="11.737" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="13.582" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="18.259" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="16.168" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="14.592" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="21.805" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="26.941" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="5.763" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.util.StringTokenizer.<init>(Unknown Source)
at java.util.StringTokenizer.<init>(Unknown Source)
at com.citi.mobileAutomation.dataMapping.KeyWords_Engine.splitBy(KeyWords_Engine.java:38)
at com.citi.mobileAutomation.dataMapping.KeyWords_Engine.returnValue(KeyWords_Engine.java:22)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:17)
at com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400.gettingDataEPP(Test__TW_EPP_Transactions_400.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="11.764" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="11.233" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="47.473" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="9.344" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="11.585" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="12.960" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="5.762" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="332.639" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="14.767" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="8.033" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="10.654" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="14.830" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="4.916" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:13)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:51)
at com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400.gettingDataEPP(Test__TW_EPP_Transactions_400.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="43.203" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="41.655" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="4.871" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:13)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:51)
at com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400.gettingDataEPP(Test__TW_EPP_Transactions_400.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="8.945" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="9.052" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="5.371" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:75)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:51)
at com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400.gettingDataEPP(Test__TW_EPP_Transactions_400.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="26.478" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="11.382" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
  <testcase name="gettingDataEPP" time="14.653" classname="com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400"/>
</testsuite> <!-- com.citi.mobileAutomation.test_EPP_TW.Test__TW_EPP_Transactions_400 -->
